# This file contains code originally from Hivemind under MIT License
# Original: Copyright 2020 Learning@home authors and collaborators
# Modified by: Pluralis Research 2026
#
# Original code: MIT License (see THIRD_PARTY_LICENSES)
# Modifications: Apache 2.0 License (see LICENSE)
#
# Licensed under the Apache License, Version 2.0 (the "License") for modifications only;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

from dataclasses import dataclass
from typing import Tuple

from agora_server.hivemind.p2p import PeerID


@dataclass(frozen=True)
class GroupInfo:
    """A group of peers assembled through decentralized matchmaking"""

    group_id: bytes  # random unique bytestring that describes the current group, generated by group leader
    peer_ids: tuple[PeerID, ...]  # an ordered sequence of peer_ids of each groupmate
    gathered: tuple[bytes, ...]  # binary metadata gathered from all peers by leader, same order as peer_ids

    @property
    def group_size(self):
        return len(self.peer_ids)

    def __contains__(self, peer_id: PeerID):
        return peer_id in self.peer_ids
